spring:
  datasource:
    url: jdbc:mysql://HOST:PORT/DB
    username: DB_USERNAME
    password: DB_PASSWORD
    hikari:
      minimumIdle: 1
      maximumPoolSize: 8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create


## If default port already in use
server:
  port: 8081
  ## Session timeout
  servlet:
    session:
      timeout:
