package com.example.demo.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table (name = "USER_TABLE")
public class User {

    @Id //key value
    @GeneratedValue //id will be automatically generated by Hibernate
    private int id;
    private String email;
    private String password;

    /*
    With Lombok constructors, getters and setters are obsolete
    can be removed later after injecting Lombok annotations
    (which wasn't done yet for clarity)
     */
    public User() {
    }

    public User(int id, String email, String password) {
        this.id = id;
        this.email = email;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
