package com.example.demo.entity;

import javax.persistence.*;

@Entity
@Table (name = "USER_TABLE")
public class User {

    @Id //key value
    @GeneratedValue(strategy = GenerationType.IDENTITY) //id will be automatically generated by Hibernate
    private int id;
    private String email;
    private String password;
    private boolean admin;
    private String name;
    private String avatar;

    /*
    With Lombok constructors, getters and setters are obsolete
    can be removed later after injecting Lombok annotations
    (which wasn't done yet for clarity)
     */

    public User() {
    }

    public User(int id, String email, String password, boolean admin, String name, String avatar) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.admin = admin;
        this.name = name;
        this.avatar = avatar;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isAdmin() {
        return admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}
